cabal-version: 3.0
name:          specter
version:       0.1.0
synopsis:      Authentic terminal primitives enabling autonomous agents to operate interactive applications.
license:       CC-BY-NC-SA-4.0
license-file:  LICENSE
build-type:    Simple

executable specter
  main-is:          Specter.hs
  hs-source-dirs:   src
  default-language: GHC2024
  ghc-options:      -threaded -O2 -Wall -Wextra -Werror -Wno-missing-signatures
  build-depends:
    , aeson
    , async
    , attoparsec
    , base
    , bytestring
    , containers
    , directory
    , http-client
    , http-client-tls
    , lens
    , network
    , posix-pty
    , process
    , stm
    , text
    , unix
    , vector


